"use strict";

var itemsUrl = 'https://api.parse.com/1/classes/items';

//create new angular module
angular.module('FoodApp', [])
	.config(function($httpProvider) {
        //Parse required two extra headers sent with every HTTP request: X-Parse-Application-Id, X-Parse-REST-API-Key
        //the first needs to be set to your application's ID value
        //the second needs to be set to your application's REST API key
        //both of these are generated by Parse when you create your application via their web site
        //the following lines will add these as default headers so that they are sent with every
        //HTTP request we make in this application
        $httpProvider.defaults.headers.common['X-Parse-Application-Id'] = 'bAO3og2I0SZxhlE7N1TC0yTNGjEYx677VvlKXmRh';
        $httpProvider.defaults.headers.common['X-Parse-REST-API-Key'] = 'rIN4tjOwmDQlyeJHn6L8CQhhpzv6OECF81ZVKEWo';
    })
    .controller('FoodController', function($scope, $http) {
        $scope.siganos = siganos;
        $scope.hotdawgs = hotdawgs;
        $scope.motosurf = motosurf;
        $scope.redsquarebbq = redsquarebbq;

        $scope.additem = function (item) {
            $scope.loading = true;
            $http.post(itemsUrl, item)
                .success(function (responseData) {
                    $scope.item.objectId = responseData.objectId;
                    $scope.items.push($scope.item);
                })
                .error(function (err) {
                    $scope.errorMessage = err;
                })
                .finally(function () {
                    $scope.loading = false;
                });
        };

        $scope.refreshItems = function () {
            $scope.loading = true;
            $http.get(itemsUrl)
                .success(function (data) {
                    $scope.items = data.results;
                })
                .error(function (err) {
                    $scope.errorMessage = err;
                })
                .finally(function () {
                    $scope.loading = false;
                });
        };

        $scope.deleteitem = function (item) {
            $http.delete(itemsUrl + '/' + item.objectId)
                .success(function (responseData) {
                    $scope.refreshItems();
                })
                .error(function (err) {
                    console.log(err);
                })
                .finally(function () {
                    //nothing needed
                })
        };

    });